---
# installing opendistro-for-kibana 0.9.0 for visualization logs

# installing dependencies for kibana
- name: install apt-transport-https
  apt: name={{ item }} state=latest
  with_items:
    - apt-transport-https 
  tags:
   - setup

# add apt-key for kibana
- name: add kibana apt-key
  apt_key:
   url: "{{ kibana_apt_key }}"
   state: present
  tags:
   - setup

# add kibana apt-repository
- name: adding kibana apt repository
  apt_repository:
   repo: "{{ kibana_apt_repository }}" 
   state: present
  tags:
   - setup

# update local cache 
- name: update local cache before installing kibana
  apt:
   update_cache: yes
  tags:
   - install

# install kibana and update the local cache 
- name: installing kibana opendistro 
  apt:
   name: opendistroforelasticsearch-kibana 
   state: present
   update_cache: yes
  tags:
   - update

# define kibana log directory
- name: define kibana log directory
  set_fact:
    log_path: /var/log/kibana
  tags:
    - update

# validate kibana log directory
- name: validate kibana log directory
  file:
    path: "{{ log_path }}"
    state: directory
    recurse: yes
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: '0755'
  tags:
    - update

# copy a customized kibana configuration file
- name: copy a customized kibana configuration file
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: '0644'
  tags:
   - update

# just force systemd to reload services
- name: just force systemd to reload services
  systemd:
    daemon_reload: yes
  tags:
    - reload

# enable kibana service
- name: enable kibana service
  systemd:
    name: kibana
    enabled: yes
  tags:
    - enable

# restart kibana service
- name: restart kibana service
  systemd:
    name: kibana
    state: restarted
  tags:
    - restart

